server/lib/puppet-languageserver/simple_tcp_server.rb

The `close_connection` method closes the connection it does not return a boolean
as indicated by the question mark at the end.  This commit removes the errant
character.

(maint) Fix incorrectly named method

---

client/languages/puppet.configuration.json
client/package.json

Previously the block commenting was configured but was not be applied.  This
commit changes the configuration to use the correct location of configuration
file.
This commit also changes the comment style to always the hash character '#' as
per the puppet language documentation.

(maint) Fix block commenting

---

server/lib/puppet-languageserver.rb
server/lib/puppet-languageserver/puppet_helper.rb

Previously on the Facter facts were preloaded.  This commit changes the
behaviour to preload Pupept Types and Functions asynchronously as well.

Add more Puppet preloading to language server

---

.gitignore
client/.gitignore
client/gulpfile.js
client/package.json

Previously the language server source files were not transferred to the client
directory so they could be consumed by the client.  This commit
- Adds four gulp tasks; build, clean, copy_language_server and  build_extension
- Moves the .gitignore from the root into the client.  The ignore file is not
needed in the root
- Gitignore in `client/` adds the vendor folder (which is where the language
server code ends up) and any generated artifacts (*.vsix) to the ignore list.
Note that the vsix filter only applies to files within the client folder, not
in the root directory.

Add Packaging task to client

---

client/.vscode/tasks.json

This adds a background task to run gulp, which builds the ruby language server, vendors it so the client can access it, and then packages the vscode extension

add a vscode task to run gulp

---

client/.vscode/tasks.json

The npm task was commented out to create the gulp task. This is needed by vscode proper, so lets put it back

fix npm task in tasks.json

---

server/lib/puppet-languageserver/completion_provider.rb
server/lib/puppet-languageserver/puppet_parser_helper.rb
server/spec/integration/puppet-languageserver/completion_provider_spec.rb

The resource completion had a trailing comma which generated invalid puppet
code.  This commit removes the errant comma.

Fix resource completion typo

---

client/.vscode/tasks.json

Previously on Windows, VSCode would not finishing compiling the client and
would never start up the extension debugging session.  This commit removes the
redudant log squashing command, which was causing VSCode to never see the
output from the compiler to say TSC had finished.

Fix task runner for v2.0.0 API

---

client/src/extension.ts
client/src/languageserver.ts
client/src/messages.ts
client/src/providers/previewNodeGraphProvider.ts
client/src/puppetcommands.ts

This cleans up extension.ts by moving out the custom Puppet Commands and Language server initialization to their own files.

Extension.ts cleanup

---

server/lib/puppet-languageserver/json_rpc_handler.rb
server/lib/puppet-languageserver/message_router.rb
server/lib/puppet-languageserver/simple_tcp_server.rb

Previously when the client sent an `exit` message, the language server would
attempt to close the underlying connection however it would hang, and at worst
cause high CPU usage.  This commit
- Uses the callback architecture inside the TCP Server to close connection
instead of trying to close the TCP Socket within the same execution context.
This stops the possibility of a race condition which can cause unexpected
blocks
- Add a missing method `close_connection_after_writing` on the base connection
class
- Add more logging on TCP startup to describe whether the server will close
after the client disconnects

Fix Language Server not stopping when client disconnects

---

server/README.md
server/lib/puppet-languageserver.rb
server/lib/puppet-languageserver/json_rpc_handler.rb
server/lib/puppet-languageserver/message_router.rb
server/lib/puppet-languageserver/simple_tcp_server.rb

Previously debug logging only happened to STDOUT.  This commit chanages all
logging commands to a unified logger variable which can either be sent to
STDOUT, a file or (by default) nothing.
This commit also fixes a bug in the connect and disconnet messages which were
silently throwing errors.

Unify debug logging

---

server/lib/puppet-languageserver/message_router.rb
server/lib/puppet-languageserver/puppet_helper.rb

Previously the output from the Puppet Resource command in the language server
did not match the output from a normal `puppet resource` invocation.  This
commit modifies the language server to mimic the behaviour from puppet-agent
by use the prune_parameters method prior to send the data back to the client.
Also and additional newline is placed between each resource for better
readability.

(GH-54) Fix Puppet Resource Command

---

server/README.md
server/lib/puppet-languageserver.rb

NOTE - This builds on https://github.com/jpogran/puppet-vscode/pull/26
Previously the TCP Server would only start after parts of Puppet were
initialised.  This commit changes the startup behaviour so that the TCP Server
is running as soon as the Puppet Version can be determined, and further
initialisation is handed to a different thread.  A new command line option of
--start-slow is added, mainly for testing, to slow down the startup if required.
This will help when the server is started by the VSCode client directly so that
the TCP socket is available as soon as possible.

Speedup server startup

---

server/lib/puppet-languageserver/puppet_helper.rb

Previously the puppet helper only loaded the core puppet types.  This commit
instead invokes the Puppet::Util::Autoload class to load all of the puppet
types.  This means that type loading is now slower, but as it has async support
this won't stop UI requests for too long.

(GH-46) Autoload modules, not just core types

---

server/lib/puppet-languageserver/message_router.rb

The didClose notification is sent when a user closes a text file in the editor.
This commit updates the language server to remove the document from the local
document store when the user closes the document.

(GH-53) Respond to 'textDocument/didClose' notification

---

server/Gemfile
server/lib/puppet-languageserver/document_validator.rb
server/spec/integration/puppet-languageserver/document_validator_spec.rb

Previously it was not possible to test on older puppet gems as the gemfile
always defaulted to latest.  This commit adds the PUPPET_GEM_VERSION
environment variable which can be used to set the version of the puppet gem
during a bundle.  This is the same workflow as regular Puppet modules.
The code used to do document validation was using the special function `_` which
was introduced in Puppet 4.9 for internationalisation.  This commit removes the
i18n function as it is not required for the language server itself and adds
some basic tests to prevent regression.

(GH-57) Fix bug with i18n in the language server

---

.travis.yml

Add travis file, using https://code.visualstudio.com/docs/extensions/testing-extensions#_running-tests-automatically-on-travis-ci-build-machines as example

(GH-12) Add Travis file

---

server/lib/puppet-languageserver/completion_provider.rb
server/lib/puppet-languageserver/puppet_parser_helper.rb
server/spec/integration/puppet-languageserver/completion_provider_spec.rb

I wanted to get a PR open to get some comments on it.
Changes
1. remove_char replaced by remove_word this allows users to get autocomplete if they start typing on a partial word such as "ens". Previously, they only received completion suggestions when typing a new word. remove_chars is left at the end of the list to facilitate completion of `$facts[`.
1. removed the `if abs_offset > 0` because it was preventing the start of the document from being interpreted as the root of a document, which meant no completion was being generated.
1. For completion only, added a check that the item isn't a `Puppet::Pops::Model::QualifiedName`, this always seems to be the "deepest" part of the AST if the user is typing a word, but it prevents useful autocompletion from being generated when typing at the …

Fix completion at file beginning on new lines and on keywords

---

appveyor.yml
client/package.json

Previously the dependency was using language server, however the actual
dependency should be languageclient which causes the packaged extension to fail
to start.  This commit changes the dependency to be languageclient.

Fix packaging JSON and appveyor

---

README.md

This commit updates the development documentation to add the Language Server
vendoring step when developing on the client.  Without this, the extension fails
to launch the server.

Update development documentation for vendoring

---

client/src/connection.ts

Previously the default behaviour was to use ruby in the path however some puppet
agent installations do not put its ruby on the path and is instead located in
/opt/puppetlabs/puppet/bin/ruby. This commit adds file detection to prefer the
specific puppet agent location of ruby and fall back to just the path.

Add better puppet-agent detection

---

appveyor.yml

With the release of Puppet 5 gem, the tests are failing due to breaking changes
in the parser/lexing APIs.  This commit modifies the Appveyor matrix to pin to
latest version of Puppet 4 for testing and optionally fail when testing on
Puppet 5

Allow Puppet 5.0 tests to fail

---

server/lib/puppet-languageserver/message_router.rb
server/spec/integration/puppet-languageserver/hover_provider_spec.rb
server/spec/spec_helper.rb
server/spec/unit/puppet-languageserver/message_router_spec.rb

This commit fixes the following errors in message router:
- The documents class had no way of clearing the document store.  This is needed
during tests
- The document store would error if a non-existant document was called.  This
commit adds a simple nil check
- The getResource request should have returned if an error was found.  This
commit adds explicit returns where required
This commit adds tests for the Hover Provider and the Message Router.  This
commit also adds helper Mock objects for the JSON RPC handler and Pupept
Resource objects which are needed in unit testing.  The `--no-preload` option
is added in spec setup to speed up tests which do not require the full Puppet
initialization, typically these are the unit tests.

Add more tests and fix minor errors in the message router

---

server/lib/puppet-languageserver/document_validator.rb

Fixes #103. This is a partial fix, we cannot parse .puppet-lint.rc files
from the module root until we have a concept of module in the extension.

(GH-103) Parse /etc and ~/ config files

---

client/README.md
client/package.json
client/snippets/metadata.snippets.json
client/src/metadata-json-schema.json

This commit adds a JSON schema document for metadata.json and applies it to any
file with the name metadata.json.  This commit also adds a snippet for any JSON
file to insert a full but blank metadata.json file with a some interactive
editting.

(GH-52) Add JSON schema for metadata.json

---

client/src/connection.ts
server/lib/puppet-languageserver.rb
server/lib/puppet-languageserver/document_validator.rb
server/lib/puppet-languageserver/message_router.rb
server/spec/integration/puppet-languageserver/document_validator_spec.rb

This adds the ability for a module-level .puppet-lint.rc file to be
honored by the language server, when the language server is started
locally with --local-workspace=PATH command
Fixes #103.

(GH-103) Parse puppet-lint.rc in module directory

---

client/package.json
client/src/connection.ts
client/src/extension.ts

This adds a configuration point to choose a custom path to the
Puppet agent. This allows non default installation paths for all
supported OS.

(GH-120) Configurable Puppet Agent directory

---

client/.gitignore
client/CHANGELOG.md
client/README.md
client/images/puppet_logo_sm.svg
client/package-lock.json
client/package.json
client/src/commands/pdk/pdkNewClassCommand.ts
client/src/commands/pdk/pdkNewModuleCommand.ts
client/src/commands/pdk/pdkTestCommand.ts
client/src/commands/pdk/pdkValidateCommand.ts
client/src/commands/pdkcommands.ts
client/src/commands/puppet/puppetResourceCommand.ts
client/src/commands/puppetcommands.ts
client/src/connection.ts
client/src/messages.ts

This adds basic support for the new PDK from Puppet
~~- [ ]  Detect platform and switch path to PDK for new module~~

adds basic PDK support

---

appveyor.yml
server/lib/puppet-languageserver/completion_provider.rb
server/lib/puppet-languageserver/hover_provider.rb

Puppet issue 7668 (https://tickets.puppetlabs.com/browse/PUP-7668) was fixed in
the puppet gem 5.2.0, which then caused parsing to work correctly.  However this
meant that root document checks were returning a BlockExpression object instead
of nil.  This commit changes the parsing so that the BlockExpression class as it
is a container for other objects and can not be auto-completed in of itself.
This commit also adds testing of Puppet gem 5.1.0 as this version of Puppet does
not contain the PUP-7668 fix and we must ensure that all puppet versions have
the same autocomplete behaviour.

Fix completion provider with Puppet 5.2.0

---

client/package.json

Previously the PuppetAgentDir default value was set to 'normal' which appears
to be a copy-paste error.  This causes the extension to try and load the
puppet language server at 'normal' in the file system which then promptly fails
on Windows.  This commit changes the default to null in JSON which then
appears in the TypeScript as undefined, and restores the previous behaviour.

(GH-120) Fix default PuppetAgentDir on Windows

---

client/src/connection.ts

Previously, when the client failed to connect to the Language Server, e.g. the
local language server crashes, the UI was not updated to say that it failed.
This was due to an error being thrown in the error handler.  This commit changes
the connection handler to use the reference to the language client instead of,
`this` which is a Socket object.

Fix incorrect logger when a client error occurs

---

client/src/providers/previewNodeGraphProvider.ts
server/lib/puppet-languageserver/message_router.rb

Previously if a node graph preview has no resources it just shows a blank
window which is very confusing.  This commit now shows a message in the window
saying;
`There were no resources created in the node graph. Is there an include statement
missing?`

(GH-140) Show a message in Node Graph preview for zero resources

---

client/package.json
client/src/commands/puppetcommands.ts
client/src/configuration.ts
client/src/connection.ts
client/src/extension.ts
client/src/logging.ts
client/src/messages.ts
server/lib/languageserver/puppet_version.rb
server/lib/puppet-languageserver/facter_helper.rb
server/lib/puppet-languageserver/message_router.rb
server/lib/puppet-languageserver/puppet_helper.rb
server/spec/unit/puppet-languageserver/message_router_spec.rb

Note - This builds on https://github.com/jpogran/puppet-vscode/pull/135
Previously the Language client had no way to know whether the langauge server
had completed loading of facts, types and functions.  This caused requests to
be blocked because of mutex locks while this information is being loaded.
This commit;
- Adds three properties which the client can use to determine the loading status
of various parts of the Language Server, with unit tests
- The puppet and facter helpers were modified to expose a *_loaded? method
- The puppet and facter helpers will now return empty datasets if they in the
process of being loaded on another thread.  This speeds up responses to the
client
The client will now query the language server periodically after connecting.
This query is for the load status …

(GH-136)(GH-61) Make client langserver better

---

client/package.json

This commit unhides all pdk commands regardless if vscode thinks a
puppet file is open or not.
When in a window that hasn't opened a Puppet file (pp or epp), the PDK
commands are not available. This was an attempt to not show commands
that can't run without being inside a PDK module directory, but has a
side effect that after running 'pdk new module' you can't use the rest
of the pdk commands without having had run one of the commands.
This removes hiding the commands until we can research how to use the
when clause better.

(GH-144) Show All PDK Commands

---

client/src/connection.ts

Previously the language server required a puppet-agent installation however
some users are not able to install a puppet-agent, but instead the PDK.  This
commit changes the connect.ts script;
- Refactors the ruby detection into two helpers, getLanguageServerFromPDK and
getLanguageServerFromPuppetAgent.  These helpers are responsible for detecting
and setting up the process creation for their respective ruby environments on
any platform type
- Removes the need for environment.bat on Windows by setting up the process env
variables at process creation
- Updates the logging to be more verbose in the detection methods
Note the functionality to actually use the PDK is currently disabled as the
configuration settings and user story need to be completed first.  However to
not lose the effort, the …

(GH-130) Prepare to use PDK ruby if puppet agent not available

---

server/spec/spec_helper.rb
server/spec/unit/puppet-languageserver/message_router_spec.rb

Previously in commit 30e8fecb683 an error message was raised for node graphs
with no resources however the unit tests were not modified for this scenario.
This commit updates the unit tests for these test scenarios.

(GH-140) Fix unit tests for zero resource node graph

---

client/src/connection.ts

Previously the connection stop method was stopping the language client and then
killing the Language Server process, however this caused a timing issue as the
client was trying to continually send a Shutdown event.  This then caused a log
storm of failed TCP events trying to send the Shutdown event to the non-existant
Server process.  This commit removes the Language Server process killing as the
spawned Server Process, by default, will automatically close when the client
disconnects.

(maint) Fix Connection Restart

---

appveyor.yml
client/gulpfile.js
client/package.json

Previously the gulp file could be used to package the extension however that is
not how the VS Code Extension tool workflow operates (vsce).  This commit
changes the tool chain so that vsce calls the gulpfile during pre-publish to
ensure the language server is updated prior to packaging.

(GH-116) Fix packaging to conform with vsce workflow

---

client/package.json

Due to the when clause used in the command palette setup for the  command, it was hidden from view to the user but available to be invoked. This commit changes visibility so now its viewable to the user

(GH-157) Activate Puppet Resource Command

---

README.md

Link was missing a '.' is all.

(DJ-165) Fix broken link in README.md

---

client/syntaxes/puppet.tmLanguage

Previously the sytnax highlighter would not highlight comments in the class
parameters section correctly.  This was compounded further if an apostrophe
was used in the comments, the highlighter would then mark the remainder of the
document as a string.  This commit adds the line_comment pattern to be available
when inside a class (or node) header definition.  The header is everything from
the word `class` to the first brace `{`.

(GH-169) Fix colourisation of comments in class params

---

client/package.json
client/src/providers/previewNodeGraphProvider.ts

Previously the Node Graph preview was calling out to an external website to do
it's graph rendering.  This commit uses a local node module to do the rendering
and removes the temporary external website method.
This fixes #88

(GH-88) Use local Graph Renderer for node graphs

---

server/lib/puppet-languageserver/message_router.rb
server/spec/integration/puppet-languageserver/message_router_spec.rb
server/spec/unit/puppet-languageserver/message_router_spec.rb

Previously when the language server crashed, no debug information would be
created which would make it difficult to diagnose issues in the field.  This
commit adds the facility to create a crash file in
%TMP%\puppet_language_server_crash.txt.
This commit also adds tests for this facility. #97

(GH-97) Create a crash file when the language server abends

---

.github/issue_template.md
.github/pull_request_template.md

This commit adds Github issue and pull request templates to help users
submit issues and contribute code.

(maint) Add Issue and Pull Request Templates

---

client/src/connection.ts

This commit removes the check for the VERSION file inside the puppet
agent install path. This was originally used as a check that you had a
valid Puppet Agent path specified, but since there are variances whether
the file exists or not or where it's located in each package for each
platform, and it doesn't provide any actual value, it makes sense to
remove it.

(GH-177) Remove version file detection

---

client/src/providers/previewNodeGraphProvider.ts

Previously vis.jz sees backslashes as escape characters, however they are not in
the DOT language.  This commit escapes any backslash (double backslash) coming
from a valid DOT file, in preparation to be rendered by viz.js.

(GH-180) Display backslashes in node graph

---

client/README.md
client/package.json

Previously the debug server would default to applying changes to the system
instead of being opt-in.  This commit changes the deafault value of noop to true
to make it safe by default.  This commit also fixes typos in the README and
credits Corey Osman with ideas behind the debug server.

(maint) Use noop by default and fix readme typo

---

client/src/commands/pdk/pdkNewTaskCommand.ts

Previously the Logging classes were changed to an interface.  This commit fixes
a missed conversion which was causing TypeScript errors.

(maint) Fix logger in PDK New Task

---

server/lib/puppet-languageserver.rb

Previously the language server would fail to load the required language server
libraries as there was a typo in the require statement.  This commit removes the
quotes around lib as it is not a string, but a string variable.

(maint) Fix typo in class loader for puppet-languageserver

---

client/README.md
client/src/connection.ts
client/src/messages.ts
server/lib/languageserver/languageserver.rb
server/lib/languageserver/location.rb
server/lib/languageserver/puppet_version.rb
server/lib/puppet-languageserver.rb
server/lib/puppet-languageserver/definition_provider.rb
server/lib/puppet-languageserver/message_router.rb
server/lib/puppet-languageserver/puppet_helper.rb
server/lib/puppet-languageserver/puppet_monkey_patches.rb
server/lib/puppet-languageserver/server_capabilities.rb
server/spec/languageserver/fixtures/environments/test-fixtures/modules/definedtypes/manifests/deftypeone.pp
server/spec/languageserver/fixtures/environments/test-fixtures/modules/definedtypes/metadata.json
server/spec/languageserver/fixtures/environments/test-fixtures/modules/testclasses/manifests/init.pp
server/spec/languageserver/fixtures/environments/test-fixtures/modules/testclasses/manifests/nestedclass.pp
server/spec/languageserver/fixtures/environments/test-fixtures/modules/testclasses/manifests/puppetclassone.pp
server/spec/languageserver/fixtures/environments/test-fixtures/modules/testclasses/metadata.json
server/spec/languageserver/integration/puppet-languageserver/definition_provider_spec.rb

Previously the Language Server did not respond to find definition requests from
the client.  This commit
* Adds a request handler for the textDocument/definition request
* A definition provider class which will extract the definition
* Monkey patch Type and Function loading so the language server can determine
where types and functions came from
* Added definition provider as a language server capability
This commit adds parsing of puppet manifests for classes and defined types for
manifests that exist in the module path.
* The classes are loading async if preload is configured
* Will respond to definition requests if a type with the same name could not be
found
---
This commit adds class loading the client UI so instead of steps 1 to 3, there
are now 4 steps (Functions, Classes, Types …

(GH-166) Add find/peek definition capability to language server

---

appveyor.yml

Previously Appveyor would tolerate rubocop failures.  However this hasn't been
stopping badly formatted code making it into master.  This commit changes
Appveyor to consider rubocop failures as failures and to fail the build if
encountered.

(maint) Make rubocop failures fatal

---

server/lib/debugserver/debug_protocol.rb
server/lib/puppet-debugserver/debug_hook_handlers.rb
server/lib/puppet-debugserver/json_handler.rb
server/lib/puppet-debugserver/message_router.rb
server/lib/puppet-debugserver/puppet_debug_session.rb
server/spec/debugserver/fixtures/environments/test-fixtures/manifests/empty.pp
server/spec/debugserver/fixtures/environments/test-fixtures/manifests/fail.pp
server/spec/debugserver/fixtures/environments/test-fixtures/manifests/kitchen_sink.pp
server/spec/debugserver/integration/puppet-debugserver/end_to_end_spec.rb
server/spec/debugserver/integration/puppet-debugserver/message_router_spec.rb
server/spec/debugserver/spec_debug_client.rb
server/spec/debugserver/spec_debug_helper.rb

Previously the evaluate hooks would be firing when the debug session was paused.
This means when doing string evaluations the POPS evaluation depth would be
modified and potentially other hooks (function, exception) would be firing in
error.  This commit guards the evaluation hooks to exit early if the session is
paused.
This commit also fixes a bug in the after evaluation hook which was decrementing
the counter back to zero, which then broke the Step Out functionality.  This
commit changes the functionality to only decrement by one per invocation.
---
Previously the sequence number was doubling instead of incrementing by one. This
was due to a previous typo.  This commit changes the increment to one.
---
Previously, generating the stack frame list was raising errors due to Puppet 4
not …

Add debug server integration tests

---

.travis.yml
server/Gemfile
server/spec/debugserver/integration/puppet-debugserver/end_to_end_spec.rb

The CFProperty gem is vendored in Puppet Agent however for the language server
it needs to be added to the development section for developers on Mac
platforms.
---
The debug server integration tests reference ruby.exe however this does not
work on linux.  This commit changes the executable used to just ruby.
---
This commit updates travis configuration to test the language server, debug
server and building the VSIX file.  Currently it only functions on the linux
containers however it can be configurated to run on the OSX builders.

(GH-196) Add ruby testing to travis

---

client/syntaxes/puppet.tmLanguage

Adds the following to the syntax highlighter:
- Puppet Plans
- Puppet Data Types
- Number literals

(GH-216) Add plan, data types and numeric literals to syntax highlighter

---

server/lib/puppet-languageserver/document_validator.rb
server/lib/puppet-languageserver/message_router.rb
server/lib/puppet-vscode/simple_tcp_server.rb
server/spec/languageserver/integration/puppet-languageserver/document_validator_spec.rb
server/spec/languageserver/unit/puppet-languageserver/message_router_spec.rb

Previously the language server thought all files were a puppet manifest.  This
commit adds a helper function to detect document type via name.  This commit
also modifies the message router to change it's responses based on the file
type.
---
Previously the language server assumed all files were Puppet manifests however
the language server also supports EPP files.  This commit adds basic validation
for EPP files (diagnostics on open and edit).

(GH-218) Add support and validation of EPP files

---

server/README.md

This commit updates the help text in the language server README to be current.
[skip ci]

(maint) Update langauge server help in README

---

appveyor.yml
client/CHANGELOG.md
client/package-lock.json
client/package.json
client/src/connection.ts
server/.rubocop.yml
server/lib/debugserver/debug_protocol.rb
server/lib/puppet-debugserver/puppet_monkey_patches.rb

Previously in commit af61569480e54 the local workspace can be passed into the
language server, however in the next commit this is removed and is not used by
the client.  This commit:
* Readds the local-workspace option if the VS Code editor is using a workspace
* Updates the minimum VSCode version to 1.15 which has the required parameter
workspaceFolders.

(GH-225) Re-add Workspace Folder detection

---

client/syntaxes/puppet.tmLanguage

This commit updates the syntax highlighting to This commit updates the syntax highlighting to glennsarti/puppet-editor-syntax@da2181a
* Fixes puppet data type highlighing being too restrictive
* Fixes inherits keyword matching beeing too overzealous
* Updates highlighting to match that used in Atom

(maint) Update syntax highlighting

---

server/lib/puppet-languageserver/completion_provider.rb
server/spec/languageserver/integration/puppet-languageserver/completion_provider_spec.rb

Previously the site keyword was not returned as a root document keyword.  Also
this was missed due to lack of testing.  This commit adds the keyword and adds
more tests for the completion provider.

(maint) Add site keyword and completion tests

---

client/CHANGELOG.md
server/lib/puppet-languageserver.rb
server/lib/puppet-languageserver/message_router.rb
server/lib/puppet-languageserver/validation_queue.rb
server/spec/languageserver/integration/puppet-languageserver/message_router_spec.rb
server/spec/languageserver/unit/puppet-languageserver/message_router_spec.rb
server/spec/languageserver/unit/puppet-languageserver/validation_queue_spec.rb

The document validation/diagnostics part of the language server is executed on
every document open or change event. While normally this is ok, when typing fast
on large documents, this can create slowness. Particularly as we add more
features which require longer running diagnostic processes.  This commit uses
a thread safe queue system which will only allow the document to exist in
the queue once.  Safeguards are also added which will ignore validation results
if the document is changed mid-validation.

(GH-231) Make document validation asynchronous

---

client/CHANGELOG.md
client/package.json
client/src/configuration.ts
client/src/connection.ts
client/src/debugAdapter.ts
client/src/interfaces.ts
server/lib/puppet-languageserver.rb
server/lib/puppet-languageserver/completion_provider.rb
server/lib/puppet-languageserver/definition_provider.rb
server/lib/puppet-languageserver/hover_provider.rb
server/lib/puppet-languageserver/puppet_helper.rb
server/lib/puppet-languageserver/puppet_helper/cache.rb
server/lib/puppet-languageserver/puppet_helper/faux_objects.rb
server/lib/puppet-languageserver/puppet_helper/file_cache.rb
server/lib/puppet-languageserver/puppet_monkey_patches.rb
server/spec/languageserver/integration/puppet-languageserver/completion_provider_spec.rb
server/spec/languageserver/integration/puppet-languageserver/definition_provider_spec.rb
server/spec/languageserver/integration/puppet-languageserver/hover_provider_spec.rb
server/spec/languageserver/integration/puppet-languageserver/puppet_helper_spec.rb
server/spec/languageserver/spec_helper.rb
server/spec/languageserver/unit/puppet-languageserver/puppet_helper/cache_spec.rb
server/spec/languageserver/unit/puppet-languageserver/puppet_helper/faux_objects_spec.rb

Previously all Puppet assets (function metdatam type metdata) was loaded directly from Puppet on every start of the Language Server.  To help with load times and reduce memory foot print;
* Adds fake/faux Puppet objects which will be populated from Puppet and be consumed by the language server
* Adds an object cache to hold the fake objects
* Adds an experimental persistence layer for the cached objects to speed up load time.

(GH-236) Use an in memory and persistent object cache for Puppet assets

---

README.md

This commit updated all references from `jpogran/puppet-vscode` to `lingua-pupuli` as well as removing any references to the `client` folder which was removed in GH-250
PR #251 must be merged first

(GH-252) Update README for Org Move

---

package-lock.json
package.json
tsconfig.json

Because this extension supports older VS Code versions, some of the node_modules
are throwing compilation errors e.g.
Module ''vscode'' has no exported member 'CompletionContext'. Did you mean ...
This commit pins the typescript, vscode-languageclient and viz.js modules to
previous versions which typescript can then compile succesfully.
This commit updates the tsconfig.json file to emulate the older extension
compilation directory.  Later commits will move this to the more usual location
of `out` and fix any other errors.

(maint) Pin node modules to older verions and fix tsconfig

---

src/commands/pdk/pdkNewClassCommand.ts
src/commands/pdk/pdkNewModuleCommand.ts
src/commands/pdk/pdkNewTaskCommand.ts
src/commands/pdk/pdkTestCommand.ts
src/commands/pdk/pdkValidateCommand.ts
src/commands/pdkcommands.ts
src/commands/puppet/puppetResourceCommand.ts
src/commands/puppetcommands.ts

This PR fixes tslint errors in all of the PDK and Puppet VSCode command pallette commands.

(maint) Fix tslint errors in VS Code commands

---

languages/puppet.configuration.json

Hello, as I mentioned in https://github.com/lingua-pupuli/puppet-vscode/issues/284, I would really like to see `#region` folding support for puppet manifests, this change adapted from https://github.com/Microsoft/vscode-python/issues/33 should handle that.

(GH-284) Added support for #region folding

---

syntaxes/puppet.tmLanguage

This commit updates the puppet grammar file to the latest commit
https://github.com/lingua-pupuli/puppet-editor-syntax/commit/633142c3343d952e55e7ddf47af26fca97808c45

(maint) Update Puppet grammar file

---

.github/ISSUE_TEMPLATE/feature_request_issue_template.md
.github/ISSUE_TEMPLATE/issue_template.md
.github/ISSUE_TEMPLATE/puppet_lint_issue_template.md
.github/ISSUE_TEMPLATE/syntax_color_issue_template.md

Previously there was only one github issue template, however github does support
multiple.  This commit adds 3 additional templates to help directory issues to
the correct location.

(maint) Improve the Issue Templates

---

gulpfile.js
package.json

Previously you had to remember to vendor the editor services before running the
extension during development.  This commit changes the npm watch task, to first
run the new npm intial task, which downloads vendored assets, if they don't
already exist.

(maint) Automatically download vendored items on watch

---

package.json
src/connection.ts

This PR fixes the logic that decides what port to connect to the LanguageServer on. Previously it would always pick a random unused port to start and connect to the language server, now it will use the port specified in the configuration if it is there.

(GH-241) Honor specified tcp port

---

README_BUILD.md
gulpfile.js

Previously it was only possible to vendor from a github release or a local
directory.  This commit adds the ability to vendor from a custom github repo
and git reference (branch, commit SHA).

(maint) Add custom git reference for vendoring

---

CHANGELOG.md
src/connection.ts

This implements tcp retry defaults for the languageclient

(GH-240) TCP Retry defaults

---

README.md
src/extension.ts

This PR adds logic to check if there is a valid Puppet Agent binary
file path configured at extension load. It will then throw an
informative error if there isn't a binary found so the user knows what
won't work without an agent.
Previously if the extension couldn't find a Puppet Agent installation or
was configured with an incorrect path, the extension silently failed to
load the language server and there wasn't much indication you're in a
broken state.

(GH-301) Fail fast if no agent installed

---

.vscode/launch.json
appveyor.yml
gulpfile.js

This PR fixes bumping the version of the extension in package.json by changing the parameter name used to specify version. It appears version is already used by the yargs package (https://github.com/yargs/yargs/blob/master/docs/api.md#versionoption-description-version) which returns the version of the yargs package instead of what you supplied.
This PR successfully makes a versioned vsix in appveyor: https://ci.appveyor.com/api/buildjobs/yeg6k3q119arvqwn/artifacts/puppet-vscode-99.99.0-appv.134.vsix
Fixes #310

(GH-310) Fix gulp bump

---

package-lock.json

In the 0.11.0 release, the package-lock.json file was left out. This
commit updates the file with the correct version.

(maint) Update package-lock with 0.11.0 version

---

CHANGELOG.md

Prior to this commit the project inconsistently applied
the [keepachangelog](https://keepachangelog.com) standard.
This commit makes several fixes to the file:
- It ensures released versions are wrapped in square
brackets.
- It ensures every release includes appropriate sub-
headings.
- It removes non-user facing information to reduce
the cognitive load on readers.
- It rewords some of the messages to be more clear
and user facing, as well as converting them to be
sentences.
This resolves #316.

(GH-316) Fix KAC violations in CHANGELOG

---

.travis.yml
.vscode/launch.json
.vscode/settings.json
appveyor.yml
package.json
src/commands/pdkcommands.ts
src/commands/puppetcommands.ts
src/connection.ts
src/debugAdapter.ts
tsconfig.json

This PR fixes the test harness to actually run both interactively and from the command line. This resolves #317 
To test (run `git clean -xfd` before each step):
- Run `npm test` without VSCode running
- Run `Extension Host` launch task
- Run `Extension Tests` launch task

(GH-317) Fix extension test harness

---

.travis.yml
package.json
src/configuration.ts
src/configuration/pathResolver.ts
src/connection.ts
src/debugAdapter.ts
src/extension.ts
src/interfaces.ts
src/rubyHelper.ts
src/test/configuration.test.ts
src/test/paths.test.ts

This PR adds PDK as a source location for the language server.
- A new configuration point is added: `puppet.installType` which reflects either PDK or Puppet-Agent, default set to `pdk`.
- A new configuration point is added: `puppet.InstallDirectory` which can refer to either a Puppet-Agent directory or a PDK directory.
- The `puppet.puppetAgentDir` configuration point has been removed
If no configuration is set by the user, the extension will look for a PDK install in the default location.

(GH-315) PDKIFY ALL THE THINGS

---

src/rubyHelper.ts

Previously the rubyHelper would use the existing environment when building the
child process for the Language Server.  However it would also set the process
environment variables as well.  This commit adds a cloning function to instead
clone the existing process environment variables, which then stops the parent
variables being modified by accident.
Fixes #343

(GH-343) Shallow clone process environment

---

package-lock.json
package.json

This commit trims whitepsace on the newly added `puppet.installType`
configuration option to make npm happy

(maint) Update package lock

---

package.json

This commit updates the minimum supported VSCode version to 1.25. This
will enable us to add the newest features added to VSCode like outline
view and the new treeview support.`

(GH-314) Update VSCode engine to 1.25

---

README.md

This commit updates the readme to explain how to use either the PDK or Puppet-Agent as a source for the extension. It also documents the new configuration options to allow this.
Fixes #354

(GH-354) Document PDK as source information

---

package.json
src/PuppetLanguageClient.ts
src/commands/puppetcommands.ts
src/configuration.ts
src/connection.ts
src/extension.ts
src/interfaces.ts
src/logging/outputchannel.ts
src/settings.ts

This commit creates the Settings interface and static methods which can parse
a workspace settings environment.  This also includes helpers for detecting
legacy or deprecated settings and can translate to the newer format.
Fixes #278

(GH-278) Use a newer sane settings layout

---

README.md
package.json
src/debugAdapter.ts
src/extension.ts
src/feature.ts
src/feature/DebugConfigurationFeature.ts

This commit adds an implementation of a DebugConfigurationProvider;
* The adapterExecutableCommand settings is created, and a command registered
which will return the command and arguments to start the Debug Adapter.  In
this case the arguments will include the ruby environment information
* The provideDebugConfigurations method just returns the same debug
configuration  as in package.json
* Modified the DebugAdapater.ts file to use the newly injected ruby information.
This means the debug adapter no longer needs to share the code from the
extension as itself.
* However an issue was found in the DebugAdapter, if it exited without sending
the appropriate terminate method, VS Code would get in a weird state which
required it to be reloaded to start debugging again.  To stop this, if the …

(GH-366) Refactor Debug Adapter

---

package.json
src/configuration.ts
src/settings.ts

This commit deprecates the puppetAgentDir setting and instead uses the
installDirectory setting name.  This will consolidate both PDK and Puppet
Agent directories, and make way for adding PDK support.
This builds on #361

(GH-315) Deprecate the puppetAgentDir setting

---

src/feature/NodeGraphFeature.ts

Previously the langauge server would optionally return a property called
dotContent when an error occured during Node Graph generation.  However the
language client always assumed that dotContent was returned.  This commit
updates the client to use an empty string if dotContent is not returned by the
server.

(maint) Fix node graph generation

---

package.json

Previously the configuration title didn't really matter but now that VSCode has
a visual settings editor, the name 'puppet' is a typo.  This commit changes the
title for the extensions settings to 'Puppet'.

(maint) Update configuration title

---

src/feature/FormatDocumentFeature.ts

Previously the FormatDocumentProvider was a Thenable style function however this
made the code a little complex.  This commit converts the function to async
style.  This commit also cleans up some minor code formatting to make the flow
more obvious.

(maint) Convert FormatDocumentProvider to async function

---

package-lock.json
package.json
src/PuppetLanguageClient.ts

This commit updates the vscode-languageclient node module to 5.1.0.  This is
needed for more recent LSP features.
This is in two commits so you can see the progression as the extension takes on major version bumps in the node module.
This also updates the vscode dev dependency to remove security vulnerabilities and to get any bug fixes.
Fixes #337

(GH-337) Update vscode-languageclient and vscode modules

---

package.json

This commit pins the vscode-extension-telemetry package to 0.0.22

(GH-334) Update vscode-extension-telemetry

---

src/PuppetLanguageClient.ts
src/PuppetStatusBar.ts
src/connection.ts
src/feature/FormatDocumentFeature.ts
src/feature/NodeGraphFeature.ts
src/feature/PuppetResourceFeature.ts
src/interfaces.ts

Previously the UI when puppet was loading implied that the extension wasn't
running, however this isn't true. This commit changes the loading and
connection status so that we know when the Language Server is running, but
partially loaded vs fully loaded.
Fixes #399

(GH-399) Update status bar loading UI

---

.github/ISSUE_TEMPLATE/issue_template.md
README.md

Previously the README prompted users to use a deprecated Puppet setting.  This
commit changes the example in the README to use the new name of the same
setting.  This commit also updates the link in the Bug Report to the correct
location in the README.
Fixes #405

(GH-405) Update README and links into the README

---

CHANGELOG.md
package-lock.json
package.json

This PR updates necessary files to release the 0.13.0 marketplace version.

(release) Release 0.13.0

---

README.md

This commit removes the Puppet class names for the document symbols that
are supported for better readability.

(GH-411) Remove class name for symbols from README

---

gulpfile.js
package-lock.json
package.json

This commit updates the node dependencies to eliminate known vulnerabilities:
- Update Gulp to 4.0
- Update gulpfile for breaking 4.0 changes
- Update loadash to 4.17.5+
- Update cryptiles to 5.1.2+

(maint) Update node dependencies

---

src/feature/NodeGraphFeature.ts

Previously the Node Graph Feature use the previewHTML API within VSCode, however
this being actively deprecated by the VSCode team.  This commit changes the
Node Graph preview to use the new WebView API [1] by creating a static HTML
rendered.  Later commits will then call the Language Server for the manifest
content and generate the required HTML.
Note that the NodeGraphFeature must track all created WebView Panels as they do
not auto dispose.  Also if a user closes a WebView Panel it disposes of the
panel object which means the parent NodeGraphProvider object must also be
disposed of.  This commit uses a simple array to track all created providers
and hooks into lifecycle events to properly manage the objects.
[1] https://code.visualstudio.com/docs/extensions/webview
---
Previously the …

(GH-422) Move from preivewHTML to Web ViewAPI

---

syntaxes/puppet.tmLanguage

This commit updates the syntax highlighting to;
https://github.com/lingua-pupuli/puppet-editor-syntax/blob/1.2.0/syntaxes/puppet.tmLanguage
Fixes #427

(GH-427) Update syntax highlighting to 1.2.0

---

package-lock.json
package.json

This commit pins the event-stream module due to a vulnerability.
https://github.com/dominictarr/event-stream/issues/116
As we only use this in gulp, pinning to an older version seems an adequate way
of dealing with this.

(maint) Pin event-stream due to malicious code

---

syntaxes/puppet.tmLanguage

This commit updates the syntax highlighting to;
https://github.com/lingua-pupuli/puppet-editor-syntax/blob/1.3.0/syntaxes/puppet.tmLanguage

(GH-431) Update syntax highlighting to 1.3.0

---

.vscodeignore

This adds CI files and github templates to the vscodeignore file.

(maint) Add uneeded files to vscodeignore

---

README.md

This commit updates references to `puppet.puppetAgentDir` to
`puppet.installDirectory` to remove references to legacy settings. It
also updates the configuration section showing the different install
directories that are stored for different platforms to not show a red
error in markdown.

(doc) Update puppet.installDirectory usage

---

README.md
src/configuration.ts
src/handlers/stdio.ts

This commit updates the default Ruby version from 2.4.0 to 2.5.1 used
when using PDK as the source for the Puppet Language Server. Ruby 2.5.1
is in PDK 1.7.1 and PDK 1.8.0 so it is safe to use as default until we
can land a feature to allow the user to pick between available PDK ruby
versions.

(GH-454) Fix PDK Ruby file path

---

languages/puppetfile-language-configuration.json
package.json
snippets/puppetfile.snippets.json
src/PuppetStatusBar.ts
src/extension.ts
src/handler.ts
syntaxes/puppetfile.cson.json

Previously the control repo configuration file (Puppetfile) was not set as
the puppet language which meant that although the Editor Services knew how
to process the file, VSCode would not send requests to it.
This commit;
* Updates the package.json to contribute a new language called `puppetfile`
which is associated with files called `Puppetfile`
* Adds a language configuration for puppetfile, which is just a copy of the
puppet configuration
* Adds syntax highlighting for Puppetfile as a copy from the ruby syntax
highlighter.  This is because Puppetfile's are actually interpretted as ruby
* Modifies the Language Client to associated puppet and puppetfile with the
Puppet Language Server
* Modifies the Status Bar to display for puppet and puppetfile language files
Fixes #295 
Fixes #288

(GH-295)(GH-288) Add puppetfile support

---

package.json
src/handlers/stdio.ts
src/handlers/tcp.ts
src/helpers/commandHelper.ts
src/settings.ts

Previously in Editor Services version 0.17.0 the --puppet-settings
parameter was introduced.  While it's kind of used by the modulepath
settings, users still couldn't modify it directly e.g. confdir.
This commit;
* Adds a settings called
puppet.editorService.puppet.confdir
puppet.editorService.puppet.environment
puppet.editorService.puppet.modulePath
puppet.editorService.puppet.vardir
* Injects this setting into the editor service commandline if set
* Deprecates the puppet.editorService.modulePath setting and instead
use ...puppet.modulePath
Fixes #453

(GH-453) Expose advanced additional Editor Service Settings

---

snippets/puppetfile.snippets.json

Previously the snippets for adding modules into the Puppetfile broke
over multiple lines.  However the more "normal" way is to always
have them on a single line.
This commit converts the snippets to use a single line.

(GH-288) Change puppetfile snippets to single line

---

README.md
package.json
src/extension.ts
src/handler.ts
src/handlers/docker.ts
src/helpers/commandHelper.ts
src/interfaces.ts
src/settings.ts

This commit adds a new connection handler for a Puppet Language Server
docker container by adding a new setting and protocol. It also extracts
common shell environment helper methods to their own static classes.
This draws heavily from the research and spike done by Michael Lombardi
in PR https://github.com/lingua-pupuli/puppet-vscode/pull/387.
Fixes #375 
Co-authored-by: Michael Lombardi <michael.t.lombardi@outlook.com>

(GH-375) Implement Docker connection handler

---

package.json

When adding support for `Puppetfile` as a language it changed the
behavior of `resourceLangId` with contributed commands. This hid any
commands with `when` clauses that use `resourceLangId` to determine
their availability. Changing the `when` clauses to use `editorLangId`
has restored these commands in both the command palatte and in the
editor menus.
Fixes #469

(GH-469) Restore puppet palatte commands

---

CHANGELOG.md
package-lock.json
package.json

(release) 0.16.0

---

package-lock.json
package.json

Due to what looks like a bug in vscode-extension-vscode 1.1.32 this commit pins
the module to 1.1.30.  The issue is tracked in the VSCode respository [1].
Once the issue is resolved, this pin can be revertted.
[1] https://github.com/Microsoft/vscode/issues/70857

(maint) Pin vscode to 1.1.30

---

src/configuration.ts
src/configuration/pdkResolver.ts
src/test/configuration/pdkResolver.test.ts

Builds on #490 
---
Previously all of the logic used to detect PDK information was contatined within
the configuration class.  This commit adds a new PDK Resolver file which
contains classes to detect all of the available ruby instances within a PDK
installation, and detect the available Puppet gem versions for each ruby
instance.
This commit modifies the configuration class to use the new PDK Resolver.
This implements the similar configuration feature of choosing the latest
PDK ruby instance to use for the Puppet Editor Services.
---

(GH-489) Dynamically detect PDK information

---

editor-components.json

This commit updates editor-syntax to 1.3.1, which is a bugfix update.

(maint) Update Editor-Syntax to 1.3.1

---

CHANGELOG.md

This commit prepares the extension for a 0.18.0 release.
Fixes #496

(GH-496) Prepare for 0.18.0 release

---

package.json

This commit introduces a new setting to allow the user to hide the
`PDK New Module` button in the Editor Title Bar.
fixes #505

(GH-505) PDK New Module Button Visibility Setting

---

package.json
src/settings.ts
src/test/configuration.test.ts

https://github.com/lingua-pupuli/puppet-vscode/issues/502
Change the PuppetInstallType default to PDK
This will reduce the number of steps to getting the plugin working now that PDK is available.
Could not do testing as detailed in the contrib guide as there are no spec tests.

(GH-502) change the default install type to PDK

---

.vscode/extensions.json

This commit updates the recommended tslint extension to
`ms-vscode.vscode-typescript-tslint-plugin`. The `eg2.tslint` extension
is deprecated.

(maint) Update recommended tslint extension

---

README.md

This PR explicitly defines what versions of Puppet work with this
extension.
Fixes #507 #508

(GH-507)(GH-508) Document Puppet Version Support

---

CHANGELOG.md
package.json

This PR adds a file watcher to the `activationEvents` that initializes the extension if there are any Puppet or metadata.json files

(GH-530) Enable Extension on Workspace files

---

src/settings.ts

The package.json lists the feature flag to be "featureFlag" with a capital F,
however the settings class expected a lowercase f.  This commit updates the
settings class to ues the expected capital F.  Without this change, no
feature flags can be set.

(maint) Fix typo for featureFlag

---

images/puppet-dag-dark.svg
images/puppet-dag-light.svg
package.json

This commit adds a dag svg that matches dark and light themes.
Fixes #546

(GH-546) Update Puppet DAG svg icon

---

README.md
package.json
src/extension.ts

This commit announces the deprecation of the 'docker protocol' support
shipped in this extension. This extension still supports the concept of
running in docker containers, but the Microsoft Remote Container
extension can do this much better.

(maint) Deprecate docker protocol

---

package-lock.json
package.json
src/extension.ts
src/feature/PuppetModuleHoverFeature.ts
src/settings.ts

This PR introduces a new hover provider for Puppet Module metadata.json files. When a user hovers over a puppet module declared in the `dependencies` list, the provider queries the Puppet Forge api for latest version information, then displays this to the user.
Fixes #534

(GH-534) Puppet Module Metadata hover provider

---

src/extension.ts

This changes the message popup that happens when a PDK or Puppet Agent
install is not found to point to the documentation website for
troubleshooting information.

(maint) Update troubleshooting link

---

.github/workflows/stale.yml

This uses a github-action to mark all issues older than 30 days without
activity as stale. It closes all messages not replied to within 5 days.

(maint) Stale issue management

---

src/feature/PuppetStatusBarFeature.ts

This commit warns the user that you cannot change the Puppet version
loaded when using a remote TCP Language Server.
Fixes #552

(WIP)(GH-552) Disallow Puppet version change with TCP Protocol

---

CHANGELOG.md
package.json

This commit updates the Editor Services to 0.22.0 and Editor Syntax to 1.3.4,
and the relevant ChangeLog entries. This commit also adds the
puppet.editorService.formatOnType.enable setting, which is introduced as part
of Editor Services 0.22.0.

(GH-567) Update Editor Services and Editor Syntax components

---

package-lock.json
package.json
src/handler.ts
src/telemetry/typings/vscode-extension-telemetry.d.ts

This commit udpates the telemetry package to 0.1.2 as well as adding the
exception method to the reporter class.

(maint) Update telemetry to v0.1.2

---

package-lock.json
package.json

This commit upgrades mocha to fix es-abstract being resolved to 1.14.0,
which was removed from npm registry.

(maint) Update mocha to latest to fix es-abstract

---

package-lock.json
package.json
src/settings.ts

This removes all deprecated settings. These settings have been
sending warnings for several releases now, it's time to remove them.
The code that detected the legacy settings and migrated them to the
newer settings has been kept, with commented out examples for future use
Fixes #585

(GH-585) Remove deprecated settings

---

.gitignore
package.json

Fixes #592 
Blocked by release of Editor Services with https://github.com/lingua-pupuli/puppet-editor-services/pull/197
---
Now that Editor Services now has support for doing dependency resolution the
extension can now take advantage of that. This commit:
* Updates Editor Services with the new version
* Adds a new setting puppet.validate.resolvePuppetfiles, with a default of true

(GH-592) Add Puppetfile resolver in Puppet-Editor-Services

---

src/handler.ts

This commit adds a listener for telemetry events from the
Language Server, and then sends them to the telemetry reporter.
Fixes #588

(GH-588) Add server telemetry pass through

---

package.json

This PR removes the lines pointing to the language configuration
files from package.json that were removed in fa2ef7c3637cab7fe15f2068fd0c2c21650171f8

(maint) Remove Language Configuration JSON entries

---

src/helpers/commandHelper.ts

Fixes #605 
Previously when passing through a module path to the language server it would
use the puppet setting `modulePath` however this is not cased correctly. This
commit uses the correct `modulepath` puppet setting.

(GH-605) Use correct setting name for module path

---

README.md

This commit cleans up the readme to use the documentation website as primary and removes all the old information.

(maint) Update README with Documentation Website links

---

languages/puppet-language-configuration.json
languages/puppetfile-language-configuration.json
package.json
src/extension.ts

In #289 I fixed properly indenting parameters after a type declaration with a title. This introduced a regression when trying to surround a token with quotes or brackets, it would instead replace the text instead of surrounding it. This happened because `surroundingPairs` was not included in the new programmatic method used. This PR reverts the previous commits, keeping the language configuration json files, and then re-adds the programmatic method
Fxies #610

(GH-610) Fix surroundingPairs

---

package-lock.json
package.json

This commit updates mocha to latest version to address security
vulenarbility in minimist. This is a development dependency, so will not
affect the use of the extension.

(maint) Update mocha to latest

---

src/extension.ts

This commit adds a warning if the `jpogran.puppet-vscode` extension is
installed while the `puppet.puppet-vscode` extension is. This can cause
a race condition where each extension tries to register at the same
time, which will produce error message popups.

(maint) Alert if jpogran.puppet-vscode installed

---

CHANGELOG.md
package.json

This commit adds a default welcome view to the Puppet Facts view if
there are no facts found.

(GH-647) Puppet Facts Welcome View

---

README.md

This commit changes the README to point to the updated extension install
gif at the puppet-vscode.github.io website.
This is pending https://github.com/lingua-pupuli/docs/pull/31 being merged

(GH-652) Update Extension Install gif

---

.github/workflows/release.yml

This commit adds a github action that publishes the extension when a
release is created in github. It requires a github secret be created
with the token allowed to publish.

(maint) Automate Publishing VS Code Extension

---

package.json

This commit fixes the typo in declaring the welcome view for the facts
view.

(maint) Fix Facts View typo

---

CHANGELOG.md
package.json

This PR removes unneeded activation points from the activationEvents field in the package.json. It was reported that the extension is activating at times when the user does not want it to, removing uncessary ones is the solution.
The Bolt commands would trigger activation of the extension when the command palate is used, even when there isn't any content in the workspace to warrant it.
The PDK Commands are only able to be used if inside a puppet module. The core activation events will cover making these commands available, so they can be removed.

(GH-649) Reduce Activation Events

---

CHANGELOG.md
src/feature/BoltFeature.ts

This commit removes the Bolt commands from the activation list and adds
a warning message notifying the user when they run the commands. It asks
the user for feedback by providing the github issue link for this
commit.

(GH-639) Deprecate Bolt commands

---

.github/workflows/release.yml

This overhauls the github release action in this project to correctly package the vsix, create a github release, and publish the vsix to the VS Code Marketplace when a tag is pushed to the github repo.
It does not populate the body of the Github Release, and leaves that for future work.

(maint) Fix Automatic Github Release

---

src/helpers/commandHelper.ts

This PR fixes a bug that occurs if the workspace path has a space or other non-standard character. This would cause a command line parsing error when trying to execute the language server.

(GH-663) Quote Workspace path

---

CHANGELOG.md
package.json
src/extension.ts
src/views/puppetfile.ts

Adds a new view to the Puppet toolbar view container that shows the puppet modules listed in the Puppetfile in the current workspace. This also adds a new command that will open the Puppetfile at the line of the selected module in the view.
**Note**: Needs an editor-services release with https://github.com/puppetlabs/puppet-editor-services/issues/256

(GH-666) Puppetfile view

---

tools/SyncProjects.ps1

This commit adds a helper script to synchronise (one-way) release projects in
the puppet-vscode repo.  Editor Services and Editor Syntax projects can also
be used if added to the Project description e.g.
editor-services: <a version>
editor-syntax: <a version>
Any notes etc. that are not in the correct milestones are automatically removed.

(maint) Adds tool to update puppet-vscode projects

---

package.json
src/settings.ts

Add more explanation to the settings for installDirectory and installType using new VS Code Settings API that explains when to use each setting. Add a guard clause early on in the activation process that warns when settings are used that are incompatible.
The extension works when there is both pdk and agent present, and when only one is present. The problem here is that the settings for the extension are not helping the user choose successful configurations and allowing mixing of settings that then produce incorrect paths to the parts of puppet we need.
The intention for auto was to not use installDirectory or installType, so that the extension would choose whether to use pdk or agent and which paths to use itself. This was intended to make the default 'happy path' the situation where a …

(GH-670) Guard installType and installDirectory

---

.github/workflows/release.yml

The package and publish steps need to use the pwsh shell to run the build commands.

(maint) Fix automated release shell

---

CHANGELOG.md
package.json

Removes the encoding and file associations from the configurationDefaults section because as of vscode 1.24, you are no longer allowed to set settings for anything outside the language the extension is providing.

(GH-678) Remove Invalid Configuration Defaults

---

src/extension.ts

This fixes a bug when a user tries to use the 'PDK new Module' button in a VS Code window that is empty or has no workspace open. This bug was introduced when the Puppetfile view was added and did not properly catch this error case.

(GH-684) Fix pdk new module activation

---

.github/workflows/release.yml
build.ps1

This adds installing psake to the release process, which the packaging build script requires.

(maint) Fix automated release packaging

---

src/forge.ts

Pull the extension version from `package.json` and populate the request header for the Puppet Forge call.

(GH-682) Set Puppet Forge api header version

---

package.json

Add an activation event for `lib/puppet` to activate when puppet modules with no puppet manifests or Puppetfiles are present. These kinds of modules have traditional type and providers that are ruby files and not puppet files.

(GH-681) Activate extension when puppet module

---

CHANGELOG.md
README.md
package.json

This commit prepares the VSCode extension for a 1.0.0 release, with that actual
date yet to be determined.

(GH-703) Prepare for 1.0.0 release

---

package-lock.json
src/extension.ts
src/feature/PuppetfileCompletionFeature.ts
src/forge.ts

This PR adds a Puppetfile CompletionItemProvider that queries the Puppet Forge for a list of matching Puppet modules, then provides a list menu to select an item.

(GH-709) Puppetfile autocomplete

---

CHANGELOG.md
package.json

This commit updates Puppet Editor Services to version 1.0.1

(maint) Update Puppet Editor Services to 1.0.1

---

CHANGELOG.md

This commit updates the CHANGELOG with changes for the 1.0.0 release.

(maint) Release 1.0.0

---

package.json

Fixes #695 
Now that Puppet Editor Services has a setting to change the on-type formatting
this commit updates the VSCode Extension to surface that setting to users.

(GH-695) Add puppet.editorService.formatOnType.maxFileSize setting

---

src/feature/PDKFeature.ts

This PR updates the `PDK New Module` command to use the native window picker instead of asking the user to enter in the fully qualified path. It also opens the newly created module inside the window the command was issued in, instead of opening a new VS Code window.
By using the native window picker, we get the correct experience on WIndows, Mac and Linxu. Even inside WSL or Remote Containers:

(GH-724) PDK New Module with Native window

---

src/helpers/commandHelper.ts

This commit adds the git binary paths to the PATH environment variable to address the missing libssp-0.dll in ffi 1.14. This can be removed once ffi 1.15 is distributed with Puppet and the PDK.

(GH-730) Fix ffi 1.14 libssp-0.dll missing with PDK 2.0

---

package.json

Pending 1.2.0 release PR - https://github.com/puppetlabs/puppet-editor-services/pull/308
---
(GH-748) Update Puppet Editor Services to 1.2.0
This commit updates PES to 1.2.0.
---
(GH-748) Update settings for Editor Services 1.2.0
This commit adds the puppet.editorService.foldingRange.enable setting which was
introduced as part of Puppet Editor Services 1.2.0.

(GH-748) Update Editor Services to 1.2.0

---

package-lock.json
package.json
src/test/suite/index.ts

This bumps the mocha testing library from v6 to v9. 
The latest version of v6 had a dependency with a vulnerability. 
See: https://github.com/puppetlabs/puppet-vscode/security/dependabot/package-lock.json/ansi-regex/open/update-logs/161020804

(maint) update mochaJs to latest version.

---

.github/workflows/release.yml
.github/workflows/vscode-ci.yml

Prior to this commit, GHA failed on an unexpected token reference.
For more info, see:
https://github.com/microsoft/vscode-vsce/issues/653
This commit updates the GHA workflows to use node 14x instead.

(MAINT) Bump GHA node version to 14x

---

src/feature/PDKFeature.ts

This commit detects if there is an existing suspended terminal named 'Puppet PDK' and uses that instead of blindly creating a new one. If no terminal is found, it creates it's own.
Previously VS Code removed all disposed terminals created by extensions on close. VS Code has since enabled suspending terminals, which persist shutting off VS Code and are reanimated when started again.
The PDK command integration was built before the possibility of terminal suspension. When this extension starts, it creates a integrated terminal to use for PDK Commands, which is then suspended on VS Code close. When it's started again, this extension creates a new terminal, resulting in duplicate terminals. Adding logic to detect existing terminals removes this problem.

Detect suspended terminal on start

---

src/feature/PDKFeature.ts
src/feature/PuppetStatusBarFeature.ts

This PR fixes the issue where a new VSCode terminal named "Puppet PDK" was created on every window reload.
This is done by moving terminal creation from the constructor of the PDK feature to the command functions themselves.
This has the consequence that the terminal is now not created when the user opens VSCode, but when a PDK command is issued from the command palette.

(GH-825) fix duplicate PDK terminals

---

.github/workflows/release.yml
.github/workflows/vscode-ci.yml

Deprecation warnings in github workflows  "Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/setup-node@v1". This commit uses actions/setup-node@v3 instead of v1.

(CONT-987) Address deprecation warnings

---

.github/workflows/release_prep.yml

This PR will now allow maintainers to specify the version of the language server to be shipped with the new vscode extension release.
Use of more concise syntax - opted for jq over sed.
When a language server release is provided -> https://github.com/puppetlabs/puppet-vscode/pull/848
When a language server release is not provided -> https://github.com/puppetlabs/puppet-vscode/pull/849/ & https://github.com/puppetlabs/puppet-vscode/actions/runs/6421160889/job/17434877805 (step is skipped)

(CAT-1422) - Add Language Server Input to release_prep

---

.eslintrc.json
src/forge.ts

This PR fixes an issue where when hovering over a module in a Puppetfile, the forge url shown would be invalid.
This PR aims to fix this by fixing the url, in the format now used in forge urls.
**Before:**
**After:**
Fixes https://github.com/puppetlabs/puppet-vscode/issues/824

(CAT-1491) - Fix broken forge urls in Puppetfile

---

package-lock.json
package.json
src/test/runtest.ts

This PR introduces the officially supported @vscode/test-electron
vscode testing package over vscode-test.
This change has come because vscode-test is no longer the preferred
choice from microsoft, and thus stopped receiving updates.
This caused regressions in our testing.
The package-lock.json is committed to define the codebase's dependencies, as per the previous practices of this repo. Like https://github.com/puppetlabs/puppet-vscode/pull/780

(maint) - Fix nightlies

---

README.md

Bump required PDK version.
A bug appeared in the puppet versions bundled with pdk v2.7.x , which was rectified in pdk v3.x, and since only the most recent major release of PDK is supported we will bump the minimum required version for PDK puppet installation type in puppet-vscode.

(maint) - Update requirements for vscode

---

CODEOWNERS
package.json

Prior to this PR, we relied on the forge api to return the bolt task schema json.
However, the endpoint in the forge has been broken for sometime, so it brought the necessity for the call to the forge api to our attention.
We have decided now to opt to retrieve it directly from GitHub ourselves, removing the need for the forge api in this case.

(bug) - Render task schema directly from GitHub

---

.github/workflows/nightly.yml
.github/workflows/vscode-ci.yml

run the ci on puppet 8 as oppose to the now unsupported puppet 6

(maint) - run ci with puppet 8 on linux

---

package-lock.json
package.json
src/handler.ts
src/handlers/stdio.ts
src/handlers/tcp.ts
src/helpers/commandHelper.ts
src/messages.ts
src/views/facts.ts
src/views/puppetfile.ts

(CAT-1707) - Bump vscode-languageclient ^9.0.0, axios ^1.0.0 & typescript ^5.0.0

---

src/feature/PuppetModuleHoverFeature.ts

This PR fixes the module hover in metadata.json. Before it was returning just `puppetlabs` i.e. the module namespace, as oppose to the entire module name for example `puppetlabs/stdlib`.
Now, this calculates the position and returns the entire string, which can they be used to query the forge api for module data.

(bug) - Fix module hover in metadata.json

---

src/feature/PuppetfileHoverFeature.ts

Fixes an issue where a valid Puppetfile which declares a module like below
```
forge 'https://forge.puppet.com'
mod 'puppetlabs/stdlib', '9.4.0'
```
would not supply hover information.
This was due to a missing replace statement in ./src/feature/PuppetfileHoverFeature.ts, which neglected to replace the `/` with a `-` to form a valid forge slug for API querying.
see https://github.com/puppetlabs/puppet-vscode/issues/878

(GH-878) - Fix Puppetfile Hover for format owner/module

---

src/extension.ts
src/test/suite/extension.test.ts

Prior to this PR, when selecting a param/prop from the dropdown completion list in puppet-vscode, the hash rocket would not be formatted inline with the rest of the document.
This PR implements a middleware to the language client, and adds a vscode API item command which allows us to execute a vscode command after the selection of the param/prop from the dropdown list. So when an param/prop is selected, we send a callback event to the language server to format the document.
This is only possible on the vscode side thanks to the vscode API, unfortunately there is no suitable events to implement this into the langauge server.
Also not possible as:
1. The LSP does not provide adamant data to the language-server to retrieve the file content and then format on the language server side
2. Even …

(CAT-1669) - Fix hashrocket allignment on completion item select

---

.github/workflows/mend.yml

(maint) - Remove redundant conditional checkout

---

package-lock.json
package.json

resolves https://security.snyk.io/vuln/SNYK-JS-AXIOS-7361793

(CAT-2021) - Bump axios >= 1.7.4

---

.github/workflows/vscode-ci.yml

(maint) Update vscode-ci codecov
