- client/package.json
- client/src/extension.ts
- client/src/providers/previewNodeGraphProvider.ts
- server/lib/languageserver/languageserver.rb
- server/lib/languageserver/puppet_compilation.rb
- server/lib/puppet-languageserver.rb
- server/lib/puppet-languageserver/message_router.rb
- server/lib/puppet-languageserver/puppet_parser_helper.rb
> Add Node Graph Preview command

- client/src/extension.ts
- client/src/messages.ts
Code format and cleanup references in extension.ts. Moved protocol messages out to seperate file.
> Cleanup extension.ts

- server/lib/puppet-languageserver/puppet_parser_helper.rb
Previously the document mangling during parsing was not producing the expected
results.  This commit;
- Fixes a bug whereby it wouldn't use the mangled document
- Adds two new mangling methods; inserting a blank string and inserting a blank
string followed by a comma
> Fix document parsing mangling

- client/package.json
- client/src/commands/puppetResourceCommand.ts
- client/src/extension.ts
- client/src/messages.ts
- client/src/providers/previewNodeGraphProvider.ts
- server/lib/languageserver/puppet_resource.rb
- server/lib/puppet-languageserver/message_router.rb
- server/lib/puppet-languageserver/puppet_helper.rb
Add puppet resource support in Language Server
> Add puppet resource support in Language Server

- client/package.json
- client/src/extension.ts
This adds configuration settings for the language server. Merge when PR #23 is merged.
> Configuration settings

- client/package.json
This adds file encoding, file associations, and inserting a last new line on save to the default config".
PR #31 should be merged first
> Add more default settings

- server/docs/language-server.md
This commit adds more information about how the language server was implemented
in ruby and which ruby files perform which task.
> Add more documentation around the language server

- server/README.md
- server/lib/puppet-languageserver/hover_provider.rb
- server/spec/integration/puppet-languageserver/hover_provider_spec.rb
Add tests, one pending, for resources in an else block
> Hover fixes for resources and facts

- client/CHANGELOG.md
Updated the changelog for 0.4.5, 0.4.2 and 0.4.0 releases.
[ci skip]
> Update changelog for current releases

- server/lib/puppet-languageserver.rb
- server/lib/puppet-languageserver/facter_helper.rb
- server/lib/puppet-languageserver/puppet_helper.rb
- server/spec/fixtures/cache/lib/puppet/parser/functions/badfile.rb
- server/spec/fixtures/cache/lib/puppet/parser/functions/badfunction.rb
- server/spec/fixtures/cache/lib/puppet/parser/functions/concat.rb
- server/spec/fixtures/confdir/puppet.conf
- server/spec/integration/puppet-languageserver/puppet_helper_spec.rb
- server/spec/spec_helper.rb
Previously type and function loading would prematurely fail and stop the
language server if a type or function load threw an error.  This appears to be
a facet of the Puppet loadall function.  This PRchanges the loading to
mimic the loadall function but instead, ignore any loading errors and continue.
This PR also adds some debug messages after types and function have
completed loading which is useful during debugging.
> (GH-98) Fix function and type loading initial fix

- client/src/connection.ts
When the language server starts locally, it will connect on a random
port to allow multiple workspaces to be open at one time. When the
connection is not identified as a local connection, it will still use
the specified settings or default.
Fixes #109.
> (GH-109) Randomize language server port when local

- client/CHANGELOG.md
- client/README.md
- client/package-lock.json
- client/package.json
- client/src/commands/puppetResourceCommand.ts
- client/src/extension.ts
- client/src/providers/previewNodeGraphProvider.ts
- client/src/telemetry/telemetry.ts
- client/src/telemetry/typings/vscode-extension-telemetry.d.ts
This adds general telemetry to the extension, and specifically addds telemetry to the puppet resource and node graph commands
> (GH-110) Add Telemetry

- .travis.yml
- client/package.json
> Fix travis testing

- client/src/extension.ts
This commit adds logic to show an upgrade message when an upgrade
occurs, and gives user an option to supress upgrade messages.
> (GH-122) Show Upgrade Message

- server/lib/puppet-languageserver/document_validator.rb
- server/spec/integration/puppet-languageserver/document_validator_spec.rb
Previously inline linting directives were not being honored by the document
validator.  This was found due to not calling the load_data method prior to
running the lint process.  This commit calls the load_data method prior to
linting and then adds a check to ignore any linting errors that were ignored by
puppet-lint.  This commit also adds tests for this scenario.
> (GH-125) Honor inline puppet lint directives

- client/CHANGELOG.md
- client/README.md
- client/package-lock.json
- client/package.json
This updates the changelog, readme, and package.json for the 0.7.0 release
> (GH-142) Release 0.7.0

- client/CHANGELOG.md
- client/package.json
> (GH-159) Release 0.7.1

- client/package.json
- client/src/commands/pdk/pdkNewTaskCommand.ts
- client/src/commands/pdkcommands.ts
- client/src/messages.ts
This commit adds the `pdk new task` command to the extension
> (GH-167) Add PDK New Task

- client/CHANGELOG.md
- client/package.json
Update changelog and package.json in preparation for 0.7.2 release
> (maint) Release 0.7.2

- server/lib/puppet-languageserver/document_validator.rb
Previosuly if an unexpected type of error came through the document validator
it would itself raise a new exception and crash the Language Server.  This was
caused by the lack of a :line or :pos method on the exception or the inner
exception.  This commit changes the detection logic to ignore any exception that
does not contain line and position information in the exception object.  These
can be ignored as they are not Puppet manifest errors but a symptom of something
else.
> (maint) Do not error in validation exception handler

- README.md
This commit removes the MTR badges
> (maint) Remove badges

- client/CHANGELOG.md
- client/package.json
This commit updates the changelog and increments the package.json
version for the 0.8.0 release
> (maint) Release 0.8.0

- client/CHANGELOG.md
This commit adds the URLs for each issue referenced in the changelog
> (maint) Fix Changelog links

- client/README.md
This commit updates the reademe to reflect what is supported in the pdk 1.3 release
> (GH-214) Update readme for pdk 1.3

- client/CHANGELOG.md
- client/package.json
Note: #247 needs to be merged first
> (maint) Release 0.10.0

- src/extension.ts
This updates the API method called to notify the user that a new version exists
> (maint) Fix extension upgrade method

- .vscode/settings.json
- src/commands/pdk/pdkNewClassCommand.ts
- src/commands/pdk/pdkNewModuleCommand.ts
- src/commands/pdk/pdkNewTaskCommand.ts
- src/commands/pdk/pdkTestCommand.ts
- src/commands/pdk/pdkValidateCommand.ts
- src/commands/pdkcommands.ts
- src/commands/puppet/puppetResourceCommand.ts
- src/commands/puppetcommands.ts
- src/configuration.ts
- src/debugAdapter.ts
- src/extension.ts
- src/logging.ts
- src/logging/file.ts
- src/logging/null.ts
- src/logging/outputchannel.ts
- src/logging/stdout.ts
- src/messages.ts
- src/rubyHelper.ts
- src/telemetry/telemetry.ts
- src/telemetry/typings/vscode-extension-telemetry.d.ts
> (maint) Fix general tslint errors

- src/PuppetConnectionMenuItem.ts
- src/PuppetLanguageClient.ts
- src/PuppetStatusBar.ts
- src/commands/puppetcommands.ts
- src/configuration.ts
- src/connection.ts
- src/debugAdapter.ts
- src/extension.ts
- src/interfaces.ts
- src/rubyHelper.ts
This PR refactors the confgiruation and invocation of the LangugeServerClient and the LanguageServer. In doing so, it enables starting the LanguageServer using `stdio` instead of `tcp`.
> Refactor Configuration

- package.json
- src/configuration.ts
- src/connection.ts
- src/debugAdapter.ts
- src/interfaces.ts
This PR adds STDIO support to the extension
This build on PR #272 so it must be merged first.
> (GH-238) Add STDIO support

- CHANGELOG.md
This commit adds a missed completed issue to the changelog.
> (maint) Update CHANGELOG with missed issues

- CHANGELOG.md
- package.json
This commit updates the changelog and package.json for the 0.11.0
release.
> (maint) Release 0.11.0

- CHANGELOG.md
- snippets/keywords.snippets.json
This commit fixes the if/else snippet by entering in the correct
increment in the tab stop.
> (GH-319) Fix if/else snippet

- package.json
This reverts commit 9a2308019217df164e48707e73580fce5223a8d3.
> Revert "(GH-314) Update VSCode engine to 1.25"

- package.json
- src/configuration.ts
- src/interfaces.ts
- src/test/configuration.test.ts
> (GH-353) Set default source to Puppet Agent

- src/connection.ts
This commit re-adds the version details to the telemetry implementation,
but not in the same exact place. This adds the capture to the closing
statement for the connection manager, which is called when the extension
stops. This allows us to send one event per 'session', and since we
include time spent we will be able to differentiate in appinsights.
> (GH-355) Re-add Telemetry

- CHANGELOG.md
- package-lock.json
- package.json
This updates the changelog and increments the extension version for release.
> (GH-356) Release 0.11.1

- CHANGELOG.md
This commit fixes the GH issue number for the PDK feature addition
> (maint) Fix CHANGELOG for 0.11.1 release

- src/PuppetStatusBar.ts
- src/extension.ts
> (maint) Remove errant console.log

- CHANGELOG.md
- package-lock.json
- package.json
> (GH-314) Update VSCode Engine to 1.27

- CHANGELOG.md
This PR adds unreleased issues to the CHANGELOG in preparation for the 0.12 release.
> (maint) Update CHANGELOG with unreleased commits

- package-lock.json
- package.json
This commit updates package.json and package-lock.json for the 0.12.0
release.
> (maint) Release 0.12.0

- src/rubyHelper.ts
Previously the RubyHelper manipulates the path environment however due to Object
property names being case sensitive it could simply be that it's called Path or
path, particularly on Windows not so much on Linux etc.. It's also possible that
there is no PATH set but unlikely.
This commit changes the Path processing be to case-insensitive and force it to
be called PATH
This commit also removes environment variables whose value is set to null or
undefined.
> (GH-400) Fix Path environment parsing for Ruby Helper

- src/extension.ts
This PR surfaces an option to disable loading the Puppet Language
Server, while still allowing the features that do not require a language
server. The first time this option is set, the user will be presented
with a message explainging what they turned off with an option to not
show this message again. The message won't be shown next time if the
user presses the button.
Fixes #335
> (GH-335) Add option to disable language server

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
This commit prepares the extension for a 0.15.0 release.
> (GH-451) Prepare for 0.15.0 release

- CHANGELOG.md
- src/configuration.ts
> (GH-480) Automatically find PDK Ruby Version

- package-lock.json
- package.json
This reverts commit 13f84e22274b69310dbb842cfb34b57d6c3533ff.
https://github.com/Microsoft/vscode/issues/70857 is now resolved.  This pin can be removed.
> Revert "(maint) Pin vscode to 1.1.30"

- package-lock.json
- package.json
This commit updates all node dependencies.
This fixes #509
> (GH-509) Update node dependencies

- package.json
> (GH-499) Setting to Disable Editor Services

- editor-components.json
This commit updates Editor Services and Editor Syntax to their latest versions; 0.19.1 and 1.3.2 respectively.
> (maint) Update Editor Components

- README.md
- package-lock.json
- package.json
- src/configuration.ts
- src/configuration/pdkResolver.ts
- src/extension.ts
- src/settings.ts
This PR will look for the default locations for PDK the Puppet-Agent, then throw the following error message 
Fixes #502
> (GH-502) Auto detect PDK or Puppet-Agent

- CHANGELOG.md
- package-lock.json
- package.json
This commit updates the changelog and package.json for the 0.18.1
release.
> (maint) Release 0.18.1

- tools/RELEASE.md
- tools/release.ps1
This commit documentats the release process for a Marketplace releas of
the Puppet Extension.
> (maint) Release documentation

- CHANGELOG.md
- editor-components.json
- package-lock.json
- package.json
- tools/RELEASE.md
- tools/release.ps1
> Release 0.19.0

- .github/CODEOWNERS
> (maint) Add CODEOWNERS

- .github/ISSUE_TEMPLATE/issue_template.md
Remove Puppet Agent as primary source and advise user to include it if
they are using it instead of the PDK.
> (maint) Update bug report ISSUE_TEMPLATE

- README.md
Add steps for how to enable debug logging in the Output panel as well as
recommendation to redact log before posting.
> (maint) Update troubleshooting steps

- package-lock.json
- package.json
- src/configuration.ts
- src/extension.ts
- src/settings.ts
> (GH-541) Check for latest PDK Version

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
> (release) 0.20.0

- src/extension.ts
This commit sends the PDK Version telemetry on start.
> (maint) Include PDK Version

- CHANGELOG.md
Corrects the 0.21.0 release version to the actual released version.
> (maint) Fix 0.21.0 Changelog release version

- psakefile.ps1
This commit makes the editor-services extract process three steps
instead of one. The first is extracting to a `tmp` folder, then moving
to the correct final folder, then deleting the `tmp` folder.
Previously `Extact-Archive` used the file name of the zip file to
determine the target folder name. This folder name is incorrect.
Fixes #579
> (GH-579) Fix build script extract path

- CHANGELOG.md
- package-lock.json
- package.json
This commit prepares the extension for 0.22.0 release.
> (GH-597) Prepare for 0.22.0 release

- package.json
This updates puppet-editor-services to 0.25.0 and puppet-editor-syntax to 1.35.0
> (maint) Update puppet-editor-services and puppet-editor-syntax to latest

- CHANGELOG.md
- src/configuration.ts
- src/handlers/tcp.ts
- src/views/facts.ts
- (GH-630) Use Cached Facts
- (maint) Fix incorrect tcp protocol detection
- (GH-631) Puppet Facts View
- (GH-630) Add Puppet ToolBar
> GH 630 cached facts

- package.json
- (maint) Update Editor Services to 0.25.0
- (maint) Update Editor Syntax to 1.36.0
Pending 0.26.0 editor-services release
> maint update editor service syntax

- CHANGELOG.md
- src/views/facts.ts
This commit adds telemetry to the facts view provider
> (maint) Update telemetry for facts

- tools/RELEASE.md
This commit updates the release process to add in updating the documentation
website repository for the new release.
> (maint) Update release process

- CHANGELOG.md
- package.json
- psakefile.ps1
- (GH-583) Change build script to github format
- (maint) Optimize build script network calls
> (GH-583) Change build script githubref and optimize build times

- CHANGELOG.md
- package-lock.json
- package.json
> (maint) Release 0.26.1

- CHANGELOG.md
- src/extension.ts
- src/feature/PuppetfileHoverFeature.ts
- (GH-674) Puppetfile forge module hover provider
> Puppetfile forge module hover provider

- src/extension.ts
- src/feature/FormatDocumentFeature.ts
- src/feature/PuppetModuleHoverFeature.ts
- src/feature/PuppetfileHoverFeature.ts
- src/forge.ts
- (maint) Extract Puppet Forge function
- (maint) Add telemetry to all features
> (maint) Refactor Forge calls to API

- package.json
- src/feature/PDKFeature.ts
- src/messages.ts
- (GH-691) Add PDK Defined Type Command
- (maint) Fix context reference to PDK New Task
- (maint) Fix calling pdk when input is null
- (maint) Refactor pdkValidate and pdkTestUnit
- (maint) Reduce duplicatated code in pdk commands
> (GH-691) PDK New Defined Type

- .github/workflows/vscode-ci.yml
This commit updates CI to point to the main branch to trigger workflows
> (maint) Update CI to point to main branch

- CHANGELOG.md
- package-lock.json
- package.json
Update changelog release links
Update to puppet-editor-syntax 1.3.7
> (maint) Release 0.28.0

- .github/workflows/vscode-ci.yml
- psakefile.ps1
- src/forge.ts
Fix the Puppetfile module hover info to display the update date, not the created date.
Fixes #705
> (GH-705) Fix Puppetfile module update date

- package.json
- src/feature/PDKFeature.ts
- src/messages.ts
> (GH-732) Add additional PDK 2.0 functions: fact and function

- .github/workflows/release.yml
- (maint) Publish to the OpenVSX gallery
> publish openvsx

- .github/ISSUE_TEMPLATE/puppet_lint_issue_template.md
Puppet Inc forked the repo and now publishes releases from their fork.
> (MAINT) correct puppet-lint url in issue template

- .github/workflows/release_prep.yml
> (maint) - Update npm install in release_prep

- README.md
Updated as per https://learn.microsoft.com/en-us/azure/devops/extend/develop/manifest?view=azure-devops
Verified the new links work.
> (BUG) - Fixes invalid badges found on marketplace

- package.json
See [here](https://github.com/puppetlabs/puppet-editor-services/blob/main/CHANGELOG.md) for language server bug fixes and features shipped with this vscode release.
> Bump puppet-editor-services to v2.0.0.

- README.md
Language server minimum requirements have been bumped, thus the requirements for vscode need bumped.
> (maint) - Update requirements for vscode

- README.md
> Maint update readme

- .github/workflows/nightly.yml
- .github/workflows/vscode-ci.yml
> (maint) - remove ci loglevel --silent

- package-lock.json
- package.json
> (maint) - bump vscode-test-electron for ci

- .github/workflows/mend.yml
> (CAT-1660) - Add mend scanning to repo

- package.json
See https://github.com/puppetlabs/puppet-editor-services/releases/tag/v2.0.1 for more details
>  Bump puppet-editor-services to v2.0.1

- package.json
> Bump puppet-editor-services to v2.0.2

- package.json
See https://github.com/puppetlabs/puppet-editor-services/releases/tag/v2.0.3 for changes included.
> (maint) - Bump puppet-editor-services to v2.0.3

- package.json
see https://github.com/puppetlabs/puppet-editor-services/releases/tag/v2.0.4 for details
> (LanguageServer) - Bump puppet-editor-services to v2.0.4

- README.md
> (maint) - Add DevX as maintainers

- .github/workflows/vscode-ci.yml
(CAT-1829) - Update ci to run on pull_request_target
pdk version: `3.0.1`
> (CAT-1829) - Update ci to run on pull_request_target

- .github/workflows/mend.yml
- .github/workflows/vscode-ci.yml
(IT-87329) - Update workflows to run on pull_request
pdk version: `3.0.1`
> (IT-87329) - Update workflows to run on pull_request

- package-lock.json
- package.json
Bumps axios
CVE-2025-27152
--
[CVE-2025-27152](https://saas-eu.whitesourcesoftware.com/Wss/WSS.html#!securityVulnerability;id=CVE-2025-27152;orgToken=da6c96bf-591c-4eed-b131-4d3c9d27a168)
> (CAT-2273) - Bump axios to >= 1.8.2
